# 🚀 Operators and Expressions

when we use c = a + b, it is an expression. <br>
in this expression, a, b and c are operands and + is the operator. <br>

In [1]:
a = 14
b = 4

## ➕, ➖, 💥 Addition, Substraction and Multiplication operator

In [2]:
print(a, "+", b, "=", a+b)
print(a, "-", b, "=", a-b)
print(a, "*", b, "=", a*b)

14 + 4 = 18
14 - 4 = 10
14 * 4 = 56


## /, //, % Division, Floor Division and Modulus operator

"/" This operator stands for float division. It returns the quotient of the division as a float, even if both operands are integers. <br>
Unlike other programming language (like java, c), where "/" always gives the integer <br>
"//" This operator stands for floor division. It returns the quotient of the division as an integer, by discarding the fractional part. <br>
"%" This operator stands for modulus. It returns the remainder of the division. <br>

In [3]:
print(a, "/", b, "=", a/b)
print(a, "//", b, "=", a//b)
print(a, "%", b, "=", a%b)

14 / 4 = 3.5
14 // 4 = 3
14 % 4 = 2


## **Exponentiation operator**
While we want to calculate the power of a number, we can use the exponentiation operator "**". <br>
It takes two operands, the base and the exponent, and returns the result of raising the base to the power of the exponent. <br>

In [5]:
print(2, "**", 5, "=", 2**5)

2 ** 5 = 32


## 🚀 Precedence of Operators

In [6]:
print (2 + 3 * 4) # 14 First multiplication took place and then addition
print ((2 + 3) * 4) # 20 First addition took place due to parenthesis and then multiplication

14
20


In [7]:
print(2 ** 3 ** 2) #

512


its 2 to the power of 3 to the power of 2. So, first 3 to the power of 2 is calculated and then 2 to the power of 9 is calculated. So, the result is 512. Because exponentiation operator is right to left associative.

In [8]:
print( 2 + 5 - 3 * 12 / 2 % 3)

7.0


first multiplication is calculated, then division, then modulus. Because multiplication, division and modulus have same precedence and they are left to right associative. Then addition and subtraction is calculated. Because they have same precedence and they are left to right associative. So, the result is 4.0

In [10]:
print(2 + (5 - (3 * 12) / (2 % (3 ** 2))))

-11.0


first exponentiation is calculated, then modulus, then multiplication, then division, then subtraction and then addition. So, the result is -11.0

## 🚀 WAP to calculate the area of a Rectangle

In [11]:
length = 15
breadth = 5

In [12]:
area = length * breadth
print("Area of Rectangle is:", area)

Area of Rectangle is: 75


## 🚀 WAP to calculate the area of a Circle

In [14]:
radius = 7
pi = 3.14
area = pi * (radius ** 2)
print("Area of Circle is:", area)

Area of Circle is: 153.86


## 🚀 WAP to calculate the area of a Rectangle using user input

In [19]:
length = int(input("Enter the length of the rectangle: "))
breadth = int(input("Enter the breadth of the rectangle: "))
area = length * breadth
print("Area of Rectangle is:", area)

Area of Rectangle is: 30
